CREATE TABLE facilities (   
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,

    CONSTRAINT chk_facility_opening_before_closing CHECK (opening_time < closing_time)
);