CREATE TABLE courts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    credits_cost NUMERIC(10, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_courts_facility
        FOREIGN KEY (facility_id)
        REFERENCES facilities(id),

    CONSTRAINT chk_courts_credits_cost_non_negative
        CHECK (credits_cost >= 0)
);