CREATE TABLE credit_transactions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    

    CONSTRAINT fk_credit_transactions_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT chk_credit_transactions_type
        CHECK (type IN ('RESERVATION', 'REFUND', 'PURCHASE')),

    CONSTRAINT chk_credit_transactions_amount_not_zero
        CHECK (amount <> 0)
);