spring:
  application:
    name: courtly

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/courtly_db}
    username: ${SPRING_DATASOURCE_USERNAME:courtly_user}
    password: ${SPRING_DATASOURCE_PASSWORD:courtly_password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    default-schema: courtly
    schemas:
      - courtly

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: courtly

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  
server:
  port: 8081